#' Output SQL transformation code 
#' 
#' Extract transformation code from \code{iv.mult()} then export to txt file "transformation_code.txt" in work directory. 
#'
#' @param vars variables which need SQL transformation code in future scoring query. 
#' @param woe WOE list generated by \code{iv.mult()}
#' @param bin Bin list generated by \code{iv.mult()} with \code{topbin=TRUE}
#' @export
#' @examples
#' iv.trans.code(vars=c("duration_woe","housing_b1"),woe=iv.mult(german_data,"gb",ivcutoff=0.05,sql=TRUE),
#'               bin=iv.mult(german_data,"gb",ivcutoff=0.05,sql=TRUE,topbin=TRUE,tbcutoff=0.2))


iv.trans.code <- function(vars,woe,bin) {
  
  if (!is.null(woe)) {
    iv_df <- rbind.fill(woe)
    
    for (n in vars) { 
      
      if(grepl("_woe",n))
      {  
        sqlstr <- paste("case",paste(iv_df[iv_df$variable==substr(n,1,nchar(n)-4),]$sql_code,collapse= "\n"),"end as",n,",\n\n")
        sink('transformation_code.txt',append=TRUE)
        cat(sqlstr)
        sink()
      } 
    }
  }
  
  if (!is.null(bin)) {
    iv_df <- rbind.fill(bin)
    
    for (n in vars) { 
      
      if(!grepl("_woe",n)) {
        
        sqlstr <- paste(paste(iv_df[grepl(as.character(n),iv_df$sql_code),]$sql_code,collapse= "\n"),",\n")
        
        sink('transformation_code.txt',append=TRUE)
        cat(sqlstr)
        sink()
      }
    }
  } 
}


